#!/bin/sh

set -eo pipefail

while true
do
  HEADERS="$(mktemp)"
  # Get event
  EVENT_DATA=$(curl -sS -LD "$HEADERS" -X GET "http://${AWS_LAMBDA_RUNTIME_API}/2018-06-01/runtime/invocation/next")
  REQUEST_ID=$(grep -Fi Lambda-Runtime-Aws-Request-Id "$HEADERS" | tr -d '[:space:]' | cut -d: -f2)

  # Execute handler from script
  RESPONSE=$(/opt/cbmbasic "$_HANDLER")

  echo "$RESPONSE"

  # Send the response
  curl -X POST -H "Content-Type: application/json" -d "$RESPONSE" http://${AWS_LAMBDA_RUNTIME_API}/2018-06-01/runtime/invocation/$REQUEST_ID/response
done
